### ISSUE TITLE
MacOS: 0.4: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by vanvught** [hippyau/rnc#3]
Hi Hip, the console output is full with the error below. 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1108)
#1      _ControlScreenState.initState.<anonymous closure> (package:rcmnode/controlnodescreen.dart:36)
#2      _rootRunUnary (dart:async/zone.dart:1436)
#3      _CustomZone.runUnary (dart:async/zone.dart:1335)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#5      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281)
#6      _rootRunUnary (dart:async/zone.dart:1444)
#7      _CustomZone.runUnary (dart:async/zone.dart:1335)
#8      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

**Comment by hippyau** [comment]
Hmm, thanks... with will be the Art-Net TC listener probably receiving while the display is being drawn, should be able to catch this.

**Comment by hippyau** [comment]
Think I have fixed this in https://github.com/hippyau/rnc/commit/98606f0e5495b737c2fc31a36c30b07852f67a37

I'll do some more work, and make a new MacOS build later tonight for you after some more UI stuff i'm working on.  Cheers

**Comment by hippyau** [comment]
New build for MacOS is available at https://github.com/hippyau/rnc/releases/tag/MacOS
