### ISSUE TITLE
artnet.txt: Returning 2 objects [not an array]

### ISSUE THREAD

**Issue by vanvught** [hippyau/rnc#5]
Hi Hip,

For `artnet.txt `, there are 2 objects returned. These are just 2 individual objects, not returned as an array. Any idea how we can fix this? Which side ;-) ? 

```
flutter: GET /json/directory: {files: {artnet.txt: Art-Net, params.txt: DMX Transmit, network.txt: Network, rconfig.txt: Remote configuration}}
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected character (at character 821)
..."destination_ip_port_d":"192.168.2.255"}}{"artnet.txt":{"map_universe0":0}}
                                            ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:870)
#2      _parseJson (dart:convert-patch/convert_patch.dart:40)
#3      JsonDecoder.convert (dart:convert/json.dart:506)
#4      JsonCodec.decode (dart:convert/json.dart:157)
#5      _ConfigScreenState.getJSONData.<anonymous closure>.<anonymous closure> (package:rcmnode/confignodescreen.dart:36)
#6      State.setState (package:flutter/src/widgets/framework.dart:1088)
#7      _ConfigScreenState.getJSONData.<anonymous closure> (package:rcmnode/confignodescreen.dart:33)
#8      _rootRunUnary (dart:async/zone.dart:1436)
<asynchronous suspension>
```
<img width="1230" alt="Schermafbeelding 2021-10-03 om 13 42 38" src="https://user-images.githubusercontent.com/4319913/135752234-07c6da13-7d87-44bb-bbbc-4aa165828e98.png">

**Comment by vanvught** [comment]
Well be solved here -> https://github.com/vanvught/rpidmx512/issues/219

**Comment by hippyau** [comment]
Sorry Arjan, I've been been dealing with some family stuff the last couple of days... Glad to see this issues sorted itself out though :)
